<template>
  <div>
    <b-form>
      <b-row>
        <b-col>
          <b-form-group
            label="Consulta"
            label-for="query"
          >
            <b-form-input
                  id="query"
                  v-model="query"
                  autocomplete="off"
            >
            </b-form-input>
          </b-form-group>
        </b-col>
        <b-col>
          <b-form-group
            label="Desde"
            label-for="from"
          >
            <datepicker
              v-model="from"
              id="from"
              name="from"
              :minimumView="'year'"
              :maximumView="'year'"
              :initialView="'year'"
              :language="languages[lang]"
              :format="'yyyy'"
              :bootstrap-styling="true"
            ></datepicker>
          </b-form-group>
        </b-col>
                <b-col>
                    <b-form-group
                        label="Hasta"
                        label-for="to"
                    >
                        <datepicker
                            v-model="to"
                            id="to"
                            name="to"
                            :minimumView="'year'"
                            :maximumView="'year'"
                            :initialView="'year'"
                            :language="languages[lang]"
                            :format="'yyyy'"
                            :bootstrap-styling="true"
                        ></datepicker>
                    </b-form-group>
                </b-col>
            </b-row>
            
            <b-row>
                <b-col>
                    <b-form-group
                        label="Precio mínimo"
                        label-for="min_price"
                    >
                        <b-form-input
                            id="min_price"
                            v-model="min_price"
                            type="number"
                            :step="1000"
                        >
                        </b-form-input>
                    </b-form-group>
                </b-col>
                <b-col>
                    <b-form-group
                        label="Precio máximo"
                        label-for="max_price"
                    >
                        <b-form-input
                            id="max_price"
                            v-model="max_price"
                            type="number"
                            :step="1000"
                        >
                        </b-form-input>
                    </b-form-group>
                </b-col>
                <b-col>
                    <b-form-group
                        label="¿Disponible?"
                        label-for="available"
                    >
                        <b-form-select
                            id="available"
                            :options="options"
                            v-model="available"
                        >
                        </b-form-select>
                    </b-form-group>
                </b-col>
      </b-row>
      <b-row>
                <b-col>
                    <b-button
                        @click.prevent="resetFilter"
                        variant="danger"
                    >
                        Restablecer filtros
                    </b-button>
                </b-col>
            </b-row>
    </b-form>
  </div>
</template>
